name: Lint Commit Messages
on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git log -1 --pretty=format:"%s" | npx commitlint
      - uses: wagoid/commitlint-github-action@v5
