name: CI

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: |
          from=$(git log --max-count=1 --pretty=format:'%H' | awk '{print $1"^"}')
          to=$(git log --max-count=1 --pretty=format:'%H' | awk '{print $1}')
          npx commitlint --from=$from --to=$to --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: |
          from=${{ github.event.pull_request.base.sha }}
          to=${{ github.event.pull_request.head.sha }}
          echo "Validating commit range: $from..$to"
          npx commitlint --from $from --to $to --verbose
